apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grafana-admin.enc.yaml
- postgres-credentials.enc.yaml
- headlamp-token.enc.yaml
- headlamp-oidc.enc.yaml
- headlamp-oidc-flux.enc.yaml
- pgadmin-credentials.enc.yaml
- n8n-credentials.enc.yaml